### ISSUE TITLE
Feature Request: Message Relay for Whisper Mafia

### ISSUE THREAD

**Issue by Mivexil** [yamikuronue/sockMafia#111]
As discussed in the Game Queue thread, I'd like to have MafiaBot be able to relay private messages to other players for the purposes of my game. The exact flow would be something like that:
1. Player A sends a private message to MafiaBot of form: "@PlayerB &lt;message content>". Both Player A and Player B need to be alive and playing the game.
2. MafiaBot sends a private message to Player B of form: "@PlayerA says: &lt;message content>".
3. MafiaBot posts a message to the Club Ded thread of form: "@PlayerA says to @PlayerB: &lt;message content>".
4. If the current phase is the day (or dusk) phase, MafiaBot posts a (preferably) GM-configurable message to the main thread. The message may include placeholders (something like {SENDER} and {RECEIVER}), which are replaced by the sending and receiving players' handles (@PlayerA and @PlayerB in this example). Skip this step during the night.
5. If all the steps were successful, MafiaBot sends a private message to Player A of form: "Confirmed". Otherwise it sends a message of form: "This message couldn't be sent: &lt;reason of failure>".

**Comment by yamikuronue** [comment]
> MafiaBot posts a message to the Club Ded thread of form: "@PlayerA says to @PlayerB: <message content>".

We don't actually keep track of which thread is Club Ded right now. Would you accept "MafiaBot includes the GM in the private chat"?

**Comment by Mivexil** [comment]
@yamikuronue Someone mentioned they'd prefer a livestream, which is why I brought it up. If it's harder to code than it's worth it, it's fine to just CC the messages to the GM, or even simply log it somewhere on disk for easier copy-and-paste.

**Comment by AccaliaDeElementia** [comment]
This is at least partially implemented now in #136, which is slated to be released in version 3.2.0

the new `!chat` command differs in some semantics from those @mivexil suggested, but should still serve nicely for most purposes.

**Comment by yamikuronue** [comment]
That's fine, I plan to implement this ticket as well in the near future. What's already implemented eases my concerns about future games working the same way, as that provides a nice generic alternative. I'm going to call this feature "Postman". 

I figure I'll have the interface look like:
`!setValue postman true` to enable postman-mode where `!chat` will not include the sender when it creates the thread with the message and the GM
`!setValue postman-cc 1234` to CC all postman messages to thread 1234
`!setValue postman-public day` to enable the CC to the main game thread during the day phase. Other values would be `night` or `all`.

I also plan to alias `whisper` and `say` with `chat`, and allow `to player` as well as `with player`. 

Though looking over this again, I realize a true postman mode would have the sender be anonymous, so maybe I need a better name for this type of communication.

**Comment by yamikuronue** [comment]
Config values:
- postman: [**off**, on, open]
- postman-cc: **0**-many threads
- postman-public: [**none**, day, night, all]

**Comment by yamikuronue** [comment]
All but public is done; public is blocked by #139

**Comment by AccaliaDeElementia** [comment]
#139 has been resolved. Blocker removed.
