### ISSUE TITLE
Some problem with adding chats

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#119]
I added chat 509 to testMafia getting this db file:

```
        "aliases": [
            "testmafia",
            "t_17966",
            "c_509",
            "c_undefined"
        ]
```

But commands in that chat are not getting a reply, either because the game does not exist (So it mutes replies) or the chat reply function didn't work.

**Comment by AccaliaDeElementia** [comment]
Does running the bot in debug mode produce any interesting looking output?

it looks like sockMafia uses `command.reply()` pretty consistency except for in the lynchPlayer handler which seems to want to explicitly post the reply in the game thread (so that's okay)
