### ISSUE TITLE
Which thread is main?

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#139]
We need a way to get the main thread out of all the threads attached to a game

**Comment by AccaliaDeElementia** [comment]
you're looking for `mafiaGameInstance.topicId`

that holds the topicId the game was created in/for (specifically the topicId that was passed to `daoInstance.createGame(topicId, name)`)

**Comment by AccaliaDeElementia** [comment]
or do you need the ability to mutate this value after creation?

**Comment by yamikuronue** [comment]
Nope, I just need to find it :)  Thanks!

**Comment by AccaliaDeElementia** [comment]
so....

close resolved?

**Comment by yamikuronue** [comment]
Yup! I just don't know how to do that via email ;)
