### ISSUE TITLE
Rethink the way we're using the DAO and Model classes

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#14]
Is there a better option?

**Comment by dreikin** [comment]
Could you expand on this?  In particular, what do you mean by a "a better option"?  (I don't mean the architecture of the option; I mean better _for what_ or _in what way_?)

**Comment by yamikuronue** [comment]
Sorry, thought I had replied well enough in-thread. I actually had some ideas here, but mostly around passing around Model objects more often. I am going to reschedule this though, because I had a thought earlier today

**Comment by dreikin** [comment]
> thought I had replied well enough in-thread.

You may well have - my memory of what we've talked about has gotten a bit scattered lately, and perhaps I forgot about it.  I'll take a look back through later today to see what I can find.  I think there may be some other stuff in-thread I want to move into proper issues anyway.

**Comment by yamikuronue** [comment]
I really want to stop making so many round trips to the database. Like, I'd like to yank out a Player, and then query it in memory: do thye belong to this game, are they alive, are they a mod, whatever. That sort of thing.
