### ISSUE TITLE
Fix: Stop erroring on E_PLAYER_EXIST

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#148]
just staph

**Comment by AccaliaDeElementia** [comment]
what's erroring on E_PLAYER_EXIST again? or is this not one for me but more a reminder ticket?

**Comment by yamikuronue** [comment]
It's a reminder. E_PLAYER_EXIST is acceptable during startup, and it's annoying me. I've got a fix in testing now :)
