### ISSUE TITLE
List votes from club ded

### ISSUE THREAD

**Issue by boomzillawtf** [yamikuronue/sockMafia#156]
Posters in Club Ded should be able to issue the `!listvotes` command and get the bot to post the current vote total into Club Ded.

**Comment by yamikuronue** [comment]
You can do this by adding the Club Ded thread to the game using `!add this to gameName`. Is that insufficient?

**Comment by AccaliaDeElementia** [comment]
my bad. i had not added club ded to the game.

E_PEBKAC
