### ISSUE TITLE
Feature: Double Voter

### ISSUE THREAD

**Issue by abarker-TDWTF** [yamikuronue/sockMafia#19]
1. **Allow Double Voters to cast their votes separately.** This needs to be done in such a way that they can follow normal voting habits without revealing their Double Voter role until they are ready.
2. **Allow Double Voters to cast both votes in a single post.** If possible, this should be down to allow a Double Voter to drop the hammer on two lynch-wagons at the same time.
3. **Allow Double Voters to change votes separately.** To minimize vote management for Double Voters, there needs to be a way for them to change either vote without needing to worry about risking a change to the other vote.
4. **Allow Double Voters to revoke one or both votes.** To simplify vote retraction for Double Voters, they should be given the ability to retract one or both votes with a single command to VoteBot.

Further discussion in [WTDWTF PM](https://what.thedailywtf.com/t/votebot-question/54011) Involving @Yamikuronue, and @dreikin.

**Comment by abarker** [comment]
On 01/18/2016 11:55 AM, abarker-TDWTF wrote:

> 1 _Allow Double Voters to cast their votes separately_ This needs to be done in such a way that they
> can follow normal voting habits without revealing their Double Voter role until they are ready
> - _Allow Double Voters to cast both votes in a single post_ If possible, this should be down to
>   allow a Double Voter to drop the hammer on two lynch-wagons at the same time
> - _Allow Double Voters to change votes separately_ To minimize vote management for Double Voters,
>   there needs to be a way for them to change either vote without needing to worry about risking a
>   change to the other vote
> - _Allow Double Voters to revoke one or both votes_ To simplify vote retraction for Double Voters,
>   they should be given the ability to retract one or both votes with a single command to VoteBot
> 
> Further discussion in WTDWTF PM https://whatthedailywtfcom/t/votebot-question/54011 Involving
> @abarker https://github.com/abarker, @Yamikuronue https://github.com/Yamikuronue, and @dreikin
> https://github.com/dreikin
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/yamikuronue/sockMafia/issues/19.

FYI, you have the wrong abarker.  You apparently want https://github.com/abarker-TDWTF,
with the suffix.

**Comment by yamikuronue** [comment]
Thanks @abarker :) @abarker-TDWTF probably got confused because on the TDWTF forums he's just plain abarker.
