### ISSUE TITLE
Enable Coveralls Tracking for Repository

### ISSUE THREAD

**Issue by AccaliaDeElementia** [yamikuronue/sockMafia#3]
Code coverage is not being tracked on coveralls.io, even though travis jobs attempts to upload results.

From the travis build logs:

```
$ test -e ./coverage/lcov.info && < ./coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
/home/travis/build/yamikuronue/sockMafia/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

Coverage tracking should be enabled on coveralls.io or this section of the travis build should be disabled.

**Comment by yamikuronue** [comment]
I added tracking, but the badge seems broked; it didn't update and coveralls says I'm not badged.

**Comment by AccaliaDeElementia** [comment]
huh... well i see the badge reports 54% which i think matches coveralls....

**Comment by AccaliaDeElementia** [comment]
oh... yeah that's werid.

i'll look into it and issue a PR.

**Comment by yamikuronue** [comment]
Seems to work now?
