### ISSUE TITLE
Alias vote for

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#36]
I'm not sure if it should do 'vote' or 'for', but 'vote for' should work, people want to use it.

**Comment by dreikin** [comment]
Additionally, we could have this allow a double voter to cast both votes at once for the same target.

**Comment by yamikuronue** [comment]
This appears to have regressed, as evidenced by @error:

```
yamibot 2 minutes ago
Who? I'm sorry, @error but your princess is in another castle.
(for is not in this game.)
```
