### ISSUE TITLE
Add Role to data model

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#38]
A player can have multiple roles in addition to properties.

**Comment by dreikin** [comment]
What types of roles are we talking about?

**Comment by yamikuronue** [comment]
A Role is something that may affect the night but does not affect the voting. A Property affects voting. So you can be a Loved Cop, or a Hated Lover Strongman

**Comment by dreikin** [comment]
Okay, and presumably we can have multiple roles per player as well.  I'm assuming we may want to use this in output, so how about something like:

`
game | player | roleType | role | description
`

Where roleType is a standardized role name, and role and description are the flavor text versions?

**Comment by yamikuronue** [comment]
See #40 , but it'd have to be pretty generic (maybe configurable? Maybe any text will do?). We need to mark which roles are in a group together as well (two cops can both investigate but two scum can't). This is just the data model though
