### ISSUE TITLE
Bot only allows one game at a time

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#6]
The database structure was set up to allow this, but before the mod commands were ready, we set it up to just read from the config in the meantime. The config bodge needs to be replaced with proper commands for creating a game, adding co-mods, et cetera

**Comment by AccaliaDeElementia** [comment]
I'll take this on as part of #137

**Comment by AccaliaDeElementia** [comment]
this should be resolved by: 200f1356c

**Comment by AccaliaDeElementia** [comment]
this is an old one....

resolved via #140
