### ISSUE TITLE
Set can only be used in-thread

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#62]
I seem to recall we used to allow this in PM? No commands can currently be used in PM. This is important, as set is virtually unusuable. 

Be sure to update the readme when this goes in.

**Comment by AccaliaDeElementia** [comment]
if you are willing to change set to take an additional parameter you could pass it the game name or id to work on, allowing you to use it from chat or club ded

something like

`!set accalia doublevoter in Bushido_Mafia`

or

`!set accalia doublevoter in 1735`

**Comment by yamikuronue** [comment]
I like that! I hadn't fixed it yet because I was struggling to find a good syntax. I keep having to remind myself natural is better than terse here
