### ISSUE TITLE
Request: Alias hyphenated commands with unhyphenated versions

### ISSUE THREAD

**Issue by RaceProUK** [yamikuronue/sockMafia#68]
Mainly because I keep forgetting the hyphen :blush:

**Comment by yamikuronue** [comment]
Most of them are: no-lynch and nolynch is aliased. What does that leave? list-votes to listVotes? 

Maybe I should make a "list" command that pops the first argument off the stack; if it's "players", it runs listplayers, if it's "votes", it runs listvotes, and if it's "all" it pops the next argument and checks again

**Comment by RaceProUK** [comment]
`list-votes` is the one I keep mistyping; if there are others, I haven't used them yet
