### ISSUE TITLE
How should we divvy up various properties and roles in the DAO?

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#70]
Conceptually, there's a property of voting, and a property of night actions, and I'm not sure if they should be one type of thing or two.Or possibly split apart acted-upon-properties (like loved/hated/unkillable) and actor-properties (like doublevoter/killing role)?

**Comment by AccaliaDeElementia** [comment]
conceptually these are very different concepts to the controller, i'm not sure they're that different to the DAO.

i was thinking of just storing a list of property tokens in the DAO and let the controller determine what the tokens actually mean to it.

i'd like to avoid putting any more logic into the DAO than absolutely necessary.

**Comment by yamikuronue** [comment]
That would result in bringing back irrelevant information, as I'll be forced to say "Give me everything you know about player X" no matter the situation. That said, it's only a little bit. So maybe that's okay?

**Comment by AccaliaDeElementia** [comment]
given that the controller would have generated the tokens to represent the various properties i'd just say it can pass a list of tokens it's interested into the call to filter out the ones it doesn't want right now.

that way the only time you'd get them all is if you omitted the filter parameter (left it undefined)

that seems to be a nice balance between simplicity in the DAO and eliminating unecessary work in the controller.

**Comment by yamikuronue** [comment]
yeah, I like that one :)
