### ISSUE TITLE
Feature request: Multiple game threads per game

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#95]
Is it possible to mark, say, the scumthread or club ded as belonging to the game, so we can use in-game actions in them?

**Comment by AccaliaDeElementia** [comment]
i believe this is ready to implement, the functionality to allow threads to be added to a game is exposed in the DAO, although no controller support for it exists at the moment.

**Comment by yamikuronue** [comment]
Oh, that's where this ticket went. Done as of 3.1.0
